### ISSUE TITLE
Keycloak upgrade 24.0.3 

### ISSUE THREAD

**Issue by lftt-tech** [sweid4keycloak/bankid4keycloak#55] opened 2024-06-17 09:12 UTC
This is not a bug, i am looking for a suggestion to upgrade the  KC version 24.0.3.

I am trying to upgrade but for when I tried to configure bankid is identity provider the in in configuration UI the client-id and secret is mandatory how to remove those mandatory field or may be  how to make this field as non  mandatory.

<img width="1441" alt="image" src="https://github.com/sweid4keycloak/bankid4keycloak/assets/142913123/86566593-1c20-4244-a2d7-558dddf5606a">

**Comment by lftt-tech** [comment] 2024-06-17 09:12
cc @ullgren

**Comment by ullgren** [comment] 2024-06-17 10:18
Unfortunately these can currently not be removed due to limitations in keycloak 24.

I've posted a issue and a pr to keycloak but it was rejected. Trying to get the time to create another approach

**Comment by ullgren** [comment] 2024-06-17 10:20
Here is the issue I field with keycloak https://github.com/keycloak/keycloak/issues/21891

**Comment by ullgren** [comment] 2024-06-17 20:10
@lftt-tech  If your fine with building your own Keycloak you can use the patch from https://github.com/keycloak/keycloak/pull/24266 or build your own admin theme that implements a similar logic.

Unfortunately I will close this issue since the problem is in Keycloak and not in the bankid idp provider.

**Closed by ullgren** 2024-06-17 20:10 UTC
Labels: question, wontfix
